// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package koverto

import (
	credentials "github.com/koverto/credentials/api"
	users "github.com/koverto/users/api"
)

type Authentication struct {
	Credential *credentials.Credential `json:"credential"`
	User       *users.User             `json:"user"`
}

type LoginResponse struct {
	Token string      `json:"token"`
	User  *users.User `json:"user"`
}

type LogoutResponse struct {
	Ok bool `json:"ok"`
}
